version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      # - node/install-packages: npm is default
      #     pkg-manager: npm
      - run:
          command: npm test
          name: Run Mocha tests
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
workflows:
  node-tests:
    jobs:
      - test
